#server:
#  port: 8081
#
#spring:
#  application:
#    name: ms-decide
#  datasource:
#    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/decision-db
#    username: ${MS_DECIDE_DB_USERNAME}
#    password: ${MS_DECIDE_DB_PASSWORD}
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        show_sql: true
#        format_sql: true
#    hibernate:
#      ddl-auto: update
#  kafka:
#    producer:
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      properties:
#        spring:
#          json:
#            type:
#              mapping: loandtosend:com.group11.msdecide.model.dto.LoanDto
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      bootstrap-servers: broker:29092
#    consumer:
#      group-id: loanEventGroup
#      properties:
#        spring:
#          json:
#            type:
#              mapping: loandto:com.group11.msdecide.model.dto.LoanDto
#            trusted:
#              packages: '*'
#      enable-auto-commit: 'false'
#      auto-offset-reset: earliest
#      bootstrap-servers: broker:29092
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#    bootstrap-servers: broker:29092
#
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://service-discovery:8088/eureka/