server:
  port: 8081

spring:
  application:
    name: ms-decide
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/decision-db
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: loandtosend:com.group11.msdecide.model.dto.LoanDto
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: localhost:9092
    consumer:
      group-id: loanEventGroup
      properties:
        spring:
          json:
            type:
              mapping: loandto:com.group11.msdecide.model.dto.LoanDto
            trusted:
              packages: '*'
      enable-auto-commit: 'false'
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update


logging:
  level:
    com: INFO

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/
