server:
  port: 8081

spring:
  application:
    name: ms-loan
  datasource:
    url: jdbc:postgresql://localhost:5432/decision-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update

#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8088/eureka/


  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: loanEventGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.type.mapping:
          loandto: com.group11.msdecide.model.dto
        spring.json.trusted.packages: "*"
      enable-auto-commit: false

    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping:
          loandtosend: com.group11.msdecide.model.dto

logging:
  level:
    com: INFO